[[shards]]
name = "shard1"
idx = 0
address = "localhost:8080"

[[shards]]
name = "shard2"
idx = 1
address = "localhost:8081"

[[shards]]
name = "shard3"
idx = 2   
address = "localhost:8082"

[[shards]]
name = "shard4"
idx = 3
address = "localhost:8083"